export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_FORM_FIELD = 'CHANGE_FORM_FIELD';
export const CLEAR_FORM_FIELDS = 'CLEAR_FORM_FIELDS';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const SET_FORM_FIELDS = 'SET_FORM_FIELDS';
export const SET_FILTER = 'SET_FILTER';
